import { useMemo, useState } from "react"
import { Activity, History, Pencil, Plus, RotateCcw, Ruler, Trash2 } from "lucide-react"
import { useAssistant } from "../assistant/store"
import { AssistantAvatar } from "../assistant/AssistantAvatar"
import { Button } from "../../components/ui/Button"
import { AnimatedNumber } from "../../components/ui/AnimatedNumber"
import { ConfirmIconAction, IconAction } from "../../components/ui/IconAction"
import { EmptyState, SectionCard, Sparkline } from "../../design-system"
import type { MeasurementType, Workout } from "./contracts"
import { computeBodyIndices, measurementSeries } from "./bodyIndices"
import { useTraining } from "./store"
import { WorkoutFormModal } from "./WorkoutFormModal"
import { MeasurementModal, SessionModal } from "./TrainingQuickLogModals"

type Tab = "workouts" | "sessions" | "measurements"
const labels: Record<MeasurementType,string>={peso:"Peso",gordura:"Gordura",altura:"Altura",cintura:"Cintura",quadril:"Quadril",braco:"Braço",coxa:"Coxa",peito:"Peito",panturrilha:"Panturrilha"}
export function TrainingScreen() {
  const training=useTraining(), assistant=useAssistant(), [tab,setTab]=useState<Tab>("workouts"), [workoutModal,setWorkoutModal]=useState<{open:boolean;edit:Workout|null}>({open:false,edit:null}), [measurementOpen,setMeasurementOpen]=useState(false), [sessionOpen,setSessionOpen]=useState(false)
  const [metric,setMetric]=useState<MeasurementType>("peso")
  const availableMetrics=useMemo(()=>(Object.keys(labels) as MeasurementType[]).filter((t)=>training.measurements.some((m)=>m.type===t)),[training.measurements])
  const activeMetric=availableMetrics.includes(metric)?metric:(availableMetrics[0]??"peso")
  const series=useMemo(()=>measurementSeries(training.measurements,activeMetric),[training.measurements,activeMetric])
  const metricUnit=useMemo(()=>training.measurements.find((m)=>m.type===activeMetric)?.unit??"",[training.measurements,activeMetric])
  const indices=useMemo(()=>computeBodyIndices(training.measurements),[training.measurements])
  return <main className="level-page mx-auto flex max-w-[1180px] flex-col gap-6 px-4 pb-24 pt-24 sm:px-6">
    <header className="level-page-header flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="level-page-title text-3xl font-semibold tracking-tight text-on-surface">Treinos</h1><p className="mt-3 text-on-surface-variant">Fichas, sessões e medidas corporais em uma linha de evolução.</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" size="md" onClick={()=>assistant.openFor("treinos")}><AssistantAvatar module="treinos" className="size-4"/>Personal Léo</Button><Button variant="secondary" size="md" onClick={()=>setMeasurementOpen(true)}><Ruler className="size-4"/>Medida</Button><Button variant="primary" size="md" onClick={()=>setSessionOpen(true)}><Activity className="size-4"/>Registrar sessão</Button></div></header>
    {training.error?<div role="alert" className="rounded-lg border border-error/35 bg-error/5 px-4 py-3 text-sm text-error">{training.error} <button className="ml-2 underline" onClick={()=>void training.refresh()}>Tentar novamente</button></div>:null}
    <section className="grid border-y border-outline-variant sm:grid-cols-3" aria-label="Resumo de treino">
      {[{label:"Treinos ativos",value:training.workouts.length},{label:"Sessões registradas",value:training.sessions.length},{label:"Medidas",value:training.measurements.length}].map((item)=><div key={item.label} className="border-b border-outline-variant px-5 py-5 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><AnimatedNumber value={item.value} animationKey={`training-${item.label}`} className="text-3xl font-semibold"/><p className="mt-2 text-sm text-muted">{item.label}</p></div>)}
    </section>
    {training.programs.length>0?<SectionCard title={training.programs.length===1?"Programa ativo":"Programas ativos"} description={`${training.programs.length} programa(s) em uso`} bodyClassName="p-0"><div className="divide-y divide-outline-variant">{training.programs.map((program)=><div key={program.id} className="px-5 py-4"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-on-surface">{program.name}</p><p className="mt-1 text-xs text-muted">Versão {program.version} · {program.focus} · {program.daysPerWeek}x/semana · {program.location}</p></div><span className="rounded-full bg-primary/10 px-2.5 py-1 text-[11px] font-semibold text-primary">Ativo</span></div><div className="mt-3 flex flex-wrap gap-2">{program.workouts.map((workout)=><span key={workout.id} className="rounded-lg border border-outline-variant px-2.5 py-1.5 text-xs text-on-surface-variant">{workout.name}</span>)}</div></div>)}</div></SectionCard>:null}
    {training.programHistory.length>0?<SectionCard title="Histórico de programas" description={`${training.programHistory.length} versão(ões)`} bodyClassName="p-0"><ul className="divide-y divide-outline-variant">{training.programHistory.map((program)=><li key={program.id} className="flex flex-col justify-between gap-3 px-5 py-4 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><span className="grid size-9 place-items-center rounded-lg bg-primary/10 text-primary"><History className="size-4"/></span><div><p className="font-semibold text-on-surface">Versão {program.version} · {program.name}</p><p className="mt-1 text-xs text-muted">{program.daysPerWeek}x/semana · {program.workouts.length} ficha(s) · {program.location}</p></div></div><Button variant="secondary" size="sm" onClick={()=>void training.restoreProgram(program.id)}><RotateCcw className="size-4"/>Restaurar</Button></li>)}</ul></SectionCard>:null}
    <div className="flex gap-1 border-b border-outline-variant" role="tablist" aria-label="Áreas de treino">{([['workouts','Treinos'],['sessions','Sessões'],['measurements','Medidas']] as const).map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)} className={`min-h-11 border-b-2 px-4 text-sm font-semibold transition-colors ${tab===id?'border-primary text-on-surface':'border-transparent text-muted hover:text-on-surface'}`}>{label}</button>)}</div>
    {tab==="workouts"?<SectionCard title="Meus treinos" description={`${training.workouts.length} fichas`} action={<Button variant="ghost" size="sm" onClick={()=>setWorkoutModal({open:true,edit:null})}><Plus className="size-4"/>Novo treino</Button>} bodyClassName="p-0">{training.workouts.length===0?<EmptyState title="Nenhum treino montado" description="Crie sua primeira ficha com metas de séries, repetições, carga e descanso." icon="fitness_center" action={<Button variant="primary" size="sm" onClick={()=>setWorkoutModal({open:true,edit:null})}>Criar treino</Button>}/>:<ul className="divide-y divide-outline-variant">{training.workouts.map((w)=><li key={w.id} className="px-5 py-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-on-surface">{w.name}</h2><p className="mt-0.5 text-xs text-muted">{w.focus||"Foco livre"} · {w.exercises.length} exercícios</p></div><div className="flex"><IconAction label="Editar treino" onClick={()=>setWorkoutModal({open:true,edit:w})}><Pencil className="size-4"/></IconAction><ConfirmIconAction label="Excluir treino" title={`Excluir “${w.name}”?`} description="A ficha será removida. Sessões já registradas permanecem no histórico." onConfirm={()=>training.removeWorkout(w.id)}><Trash2 className="size-4"/></ConfirmIconAction></div></div><div className="mt-3 grid gap-1 sm:grid-cols-2">{w.exercises.slice(0,6).map((e)=><div key={e.id} className="flex justify-between gap-3 text-sm"><span className="truncate text-on-surface-variant">{e.name}</span><span className="numeric-value shrink-0 text-xs text-muted">{e.sets??'—'} × {e.reps??'—'}{e.loadKg?` · ${e.loadKg} kg`:''}</span></div>)}</div></li>)}</ul>}</SectionCard>:null}
    {tab==="sessions"?<SectionCard title="Histórico de sessões" description="Progressão por modalidade" bodyClassName="p-0">{training.sessions.length===0?<EmptyState title="Sem sessões registradas" description="Use o log rápido para registrar força, cardio, calistenia ou mobilidade." icon="history" action={<Button variant="primary" size="sm" onClick={()=>setSessionOpen(true)}>Registrar sessão</Button>}/>:<ul className="divide-y divide-outline-variant">{training.sessions.map((s)=><li key={s.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><p className="font-semibold text-on-surface">{s.name}</p><p className="mt-1 text-xs capitalize text-muted">{s.modality} · {new Date(`${s.date}T12:00:00`).toLocaleDateString('pt-BR')}</p></div><div className="text-right"><p className="numeric-value text-sm">{s.exercises[0]?.distanceKm?`${s.exercises[0].distanceKm} km`:s.exercises[0]?.loadKg?`${s.exercises[0].loadKg} kg`:s.durationSec?`${Math.round(s.durationSec/60)} min`:`${s.exercises[0]?.sets??'—'} × ${s.exercises[0]?.reps??'—'}`}</p><ConfirmIconAction label="Excluir sessão" title="Excluir sessão?" description="O XP concedido por esta sessão também será reconciliado." onConfirm={()=>training.removeSession(s.id)}><Trash2 className="size-4"/></ConfirmIconAction></div></li>)}</ul>}</SectionCard>:null}
    {tab==="measurements"?<SectionCard title="Índices corporais" description="Calculados das suas últimas medidas" bodyClassName="p-0">
      {indices.bmi||indices.whr||indices.weightDelta||indices.composition||indices.waterTarget?<><div className="grid divide-y divide-outline-variant sm:grid-cols-3 sm:divide-x sm:divide-y-0">
        <div className="px-5 py-4"><p className="text-xs text-muted">IMC</p>{indices.bmi?<><p className="numeric-value mt-1 text-2xl font-semibold text-on-surface">{indices.bmi.value.toLocaleString("pt-BR",{maximumFractionDigits:1})}</p><p className="mt-0.5 text-xs text-on-surface-variant">{indices.bmi.label}</p></>:<p className="mt-1 text-sm text-muted">Registre peso e altura</p>}</div>
        <div className="px-5 py-4"><p className="text-xs text-muted">Cintura ÷ quadril</p>{indices.whr?<><p className="numeric-value mt-1 text-2xl font-semibold text-on-surface">{indices.whr.value.toLocaleString("pt-BR",{maximumFractionDigits:2})}</p><p className="mt-0.5 text-xs text-on-surface-variant">{indices.whr.label}</p></>:<p className="mt-1 text-sm text-muted">Registre cintura e quadril</p>}</div>
        <div className="px-5 py-4"><p className="text-xs text-muted">Variação de peso</p>{indices.weightDelta?<><p className={`numeric-value mt-1 text-2xl font-semibold ${indices.weightDelta.value<0?"text-tertiary":indices.weightDelta.value>0?"text-on-surface":"text-on-surface"}`}>{indices.weightDelta.value>0?"+":""}{indices.weightDelta.value.toLocaleString("pt-BR",{maximumFractionDigits:1})} kg</p><p className="mt-0.5 text-xs text-on-surface-variant">desde {new Date(`${indices.weightDelta.sinceDate}T12:00:00`).toLocaleDateString("pt-BR")}</p></>:<p className="mt-1 text-sm text-muted">Registre 2+ pesos</p>}</div>
      </div>
      {indices.composition||indices.waterTarget?<div className="grid divide-y divide-outline-variant border-t border-outline-variant sm:grid-cols-3 sm:divide-x sm:divide-y-0">
        <div className="px-5 py-4"><p className="text-xs text-muted">Massa magra</p>{indices.composition?<><p className="numeric-value mt-1 text-2xl font-semibold text-on-surface">{indices.composition.leanMass.toLocaleString("pt-BR",{maximumFractionDigits:1})} kg</p><p className="mt-0.5 text-xs text-on-surface-variant">músculo, osso e água</p></>:<p className="mt-1 text-sm text-muted">Registre peso e % de gordura</p>}</div>
        <div className="px-5 py-4"><p className="text-xs text-muted">Massa gorda</p>{indices.composition?<><p className="numeric-value mt-1 text-2xl font-semibold text-on-surface">{indices.composition.fatMass.toLocaleString("pt-BR",{maximumFractionDigits:1})} kg</p><p className="mt-0.5 text-xs text-on-surface-variant">{indices.composition.fatPct.toLocaleString("pt-BR",{maximumFractionDigits:1})}% do peso</p></>:<p className="mt-1 text-sm text-muted">Registre % de gordura</p>}</div>
        <div className="px-5 py-4"><p className="text-xs text-muted">Referência de hidratação</p>{indices.waterTarget?<><p className="numeric-value mt-1 text-2xl font-semibold text-on-surface">{indices.waterTarget.liters.toLocaleString("pt-BR",{maximumFractionDigits:1})} L/dia</p><p className="mt-0.5 text-xs text-on-surface-variant">Estimativa geral de 35 ml × {indices.waterTarget.basedOnKg.toLocaleString("pt-BR",{maximumFractionDigits:1})} kg</p></>:<p className="mt-1 text-sm text-muted">Registre seu peso</p>}</div>
      </div>:null}
      </>:<p className="px-5 py-4 text-sm text-muted">Registre peso, altura, cintura e quadril para calcular IMC e relação cintura-quadril.</p>}
    </SectionCard>:null}
    {tab==="measurements"?<div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><SectionCard title="Evolução corporal" description={series.values.length?`${labels[activeMetric]} · ${series.values.length} registros`:"Sem dados"}>{availableMetrics.length>1?<div className="mb-4 flex flex-wrap gap-1.5" aria-label="Medida exibida no gráfico">{availableMetrics.map((t)=><button key={t} type="button" aria-pressed={activeMetric===t} onClick={()=>setMetric(t)} className={`min-h-11 rounded-full border px-3 text-xs font-medium transition-colors focus-visible:outline-2 focus-visible:outline-primary ${activeMetric===t?"border-primary bg-primary/10 text-primary":"border-outline-variant text-muted hover:text-on-surface"}`}>{labels[t]}</button>)}</div>:null}{series.values.length?<><div className="mb-3 flex items-baseline gap-2"><AnimatedNumber value={series.values.at(-1)??0} animationKey={`training-latest-${activeMetric}`} formatValue={(v)=>`${v.toLocaleString('pt-BR',{maximumFractionDigits:1})} ${metricUnit}`} className="text-3xl font-semibold"/><span className="text-xs text-muted">último registro</span></div><Sparkline values={series.values} labels={series.labels} valueFormatter={(v)=>`${v.toLocaleString('pt-BR')} ${metricUnit}`} height={150}/></>:<EmptyState title="Registre sua primeira medida" description="A série temporal aparecerá aqui." icon="monitor_weight" action={<Button variant="primary" size="sm" onClick={()=>setMeasurementOpen(true)}>Registrar</Button>}/>}</SectionCard><SectionCard title="Últimas medidas" description="Mais recentes" bodyClassName="p-0"><ul className="divide-y divide-outline-variant">{training.measurements.slice(0,9).map((m)=><li key={m.id} className="flex items-center justify-between px-5 py-3"><div><p className="text-sm text-on-surface">{labels[m.type]}</p><p className="text-xs text-muted">{new Date(`${m.date}T12:00:00`).toLocaleDateString('pt-BR')}</p></div><span className="numeric-value text-sm">{m.value.toLocaleString('pt-BR')} {m.unit}</span></li>)}</ul></SectionCard></div>:null}
    <WorkoutFormModal open={workoutModal.open} initial={workoutModal.edit} onClose={()=>setWorkoutModal({open:false,edit:null})} onSave={(value)=>void(workoutModal.edit?training.updateWorkout(value):training.addWorkout(value))}/>
    <MeasurementModal open={measurementOpen} onClose={()=>setMeasurementOpen(false)} onSave={training.addMeasurement}/><SessionModal open={sessionOpen} workouts={training.workouts} onClose={()=>setSessionOpen(false)} onSave={training.addSession}/>
  </main>
}
